### ISSUE TITLE
Not downloading - Can't select download folder

### ISSUE THREAD

**Issue by TobiasReich** [aclap-dev/vdhcoapp#138]
Using Arch Linux I installed the companion app (via AUR). However when trying to download something, the process never starts (it is not the source, when I used Ubuntu it worked fine). Instead it stands at 0%.
I was thinking of changing the download folder perhaps (assuming permission issues) but when I click on the configuration in order to select the download folder, the drop down menu is empty (just a few white pixels).
Any idea what is going on? I still think there is some permission issue happening but I'm not sure where to change something.

**Comment by xiota** [comment]
There's a problem with the npm modules.  It gives this error:
```
pkg/prelude/bootstrap.js:1359
      throw error;
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /snapshot/vdhcoapp/node_modules/flatted/cjs/index.js
require() of ES modules is not supported.
require() of /snapshot/vdhcoapp/node_modules/flatted/cjs/index.js from /snapshot/vdhcoapp/node_modules/log4js/lib/LoggingEvent.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /snapshot/vdhcoapp/node_modules/flatted/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snapshot/vdhcoapp/node_modules/log4js/lib/LoggingEvent.js:4:17)
    at Module._compile (pkg/prelude/bootstrap.js:1433:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by paulrouget** [comment]
This should be fixed in master. Should be part of the incoming release.
